kind: Service
apiVersion: v1
metadata:
  name: servicerequestSvc-service
spec:
  type: NodePort
  selector:
    app: servicerequestSvc
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: servicerequestSvc-deployment
  labels:
    app: servicerequestSvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servicerequestSvc
  template:
    metadata:
      labels:
        app: servicerequestSvc
    spec:
      containers:
      - name: servicerequestSvc
        image: $IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080