# NOT USED. Instead create from key value txt file 
apiVersion: v1
kind: ConfigMap
metadata:
  name: servicerequest-springapp-props
data:
  props.gitbranch: release       
  props.env: stg              

    